### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar una pelicula por id
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Recuperar todas as peliculas por un genero
GET http://localhost:1234/movies?genre=Action

### Crear una pelicula con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "Cars",
    "year": 2006,
    "director": "Gonzalo Pulido",
    "duration": 116,
    "poster": "https://pics.filmaffinity.com/Cars-746710621-large.jpg",
    "genre": [
      "Adventure",
      "Animation"
    ]
    
}

### Actualizar una pelicula
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "title": "hola",
    "year": 1990
}